name: RickyAndMortyApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0

    - name: Clean build folder
      run: |
        xcodebuild clean -project RickyAndMortyApp/RickyAndMortyApp.xcodeproj -scheme RickyAndMortyApp -configuration Debug

    - name: Build the app
      run: |
        xcodebuild build -project RickyAndMortyApp/RickyAndMortyApp.xcodeproj -scheme RickyAndMortyApp -sdk iphonesimulator -configuration Debug
