name: RickyAndMortyApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up the Xcode environment
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0

    # Step 3: Clean the build folder
    - name: Clean build folder
      run: |
        xcodebuild clean -project RickyAndMortyApp/RickyAndMortyApp.xcodeproj -scheme RickyAndMortyApp -configuration Debug

    # Step 4: Build the app
    - name: Build the app
      run: |
        xcodebuild build -project RickyAndMortyApp/RickyAndMortyApp.xcodeproj -scheme RickyAndMortyApp -sdk iphonesimulator -configuration Debug
